# tests/rhosocial/activerecord_bigquery_test/feature/backend/ddl/test_identity_policy_pins.py
"""Policy pins for the two BigQuery identity decisions of 2026-10-07.

These are **policy pins, not capability assertions**. Each test pins a
decision the project made deliberately; a failure here means the decision was
changed, not that a new fact was discovered. Whoever intends to flip a pin must
edit the named test in the same commit and say why -- the pin exists so the
change cannot happen silently.

Pinned decisions (``.claude/plan/2026-10-07/identity-gaps.md``):

1. ``supports_identity_column()`` stays ``True`` while the service feature is
   in Preview: the probe answers "can this dialect express the clause", not
   "is the clause GA".
2. The bare clause stays ``AS IDENTITY ()``: the grammar's parentheses are
   literal, and only their contents are optional.

**Not server-verified.** There is no BigQuery instance in this environment.
Both pins are documentation comparisons (identity-columns page, DDL and DML
references, release notes and the announcement blog, all fetched 2026-10-07),
and the ``AS IDENTITY ()`` pin is the one assertion in the round that cannot be
execution-confirmed at all. One query against a real connection would settle
it.
"""

from rhosocial.activerecord.backend.expression.statements import ColumnDefinition
from rhosocial.activerecord.backend.expression.types import IntegerType
from rhosocial.activerecord.backend.impl.bigquery.dialect import BigQueryDialect
from rhosocial.activerecord.base import IdentityAttribute


def _bare_identity_column(dialect):
    column = ColumnDefinition(dialect, "id", IntegerType(dialect))
    column.attributes = [IdentityAttribute()]
    return column


class TestIdentityPolicyPins:
    """Deliberate decisions, not capability claims. Read before editing.

    If one of these tests fails, the production code and the pin disagree.
    Fixing that by relaxing the pin defeats its purpose: either revert the
    production change, or change the policy and edit the pin deliberately,
    explaining the change.
    """

    def test_policy_pin_probe_stays_true_while_the_feature_is_in_preview(self):
        """Decision 1: ``supports_identity_column()`` answers ``True``.

        BigQuery's identity columns are Preview (shipped 2026-08-31, Pre-GA
        terms, project enablement required). The dialect still declares the
        capability because the probe answers "can this dialect express the
        clause", not "is the clause GA". Flipping this to ``False`` is a policy
        change, and the probe's docstring -- asserted below to keep carrying
        the Preview status and its source -- is part of the pin.
        """
        dialect = BigQueryDialect()
        assert dialect.supports_identity_column() is True

        doc = type(dialect).supports_identity_column.__doc__
        assert doc is not None
        assert "Preview" in doc
        assert "2026-08-31" in doc
        assert "policy" in doc.lower()
        assert "https://cloud.google.com/bigquery/docs/identity-columns" in doc

    def test_policy_pin_bare_clause_keeps_the_literal_empty_paren_group(self):
        """Decision 2: the bare clause renders ``AS IDENTITY ()``.

        The DDL grammar puts the parentheses outside the optional-clause
        brackets, so they are literal and only their contents are optional. No
        official material shows the paren group empty, which makes this the
        round's one assertion that cannot be execution-confirmed; it stays as
        the documented reading until a real connection can answer. The
        formatter's docstring is part of the pin too, asserted below to keep
        the basis.
        """
        dialect = BigQueryDialect()
        assert _bare_identity_column(dialect).to_sql()[0] == (
            "`id` INT64 GENERATED BY DEFAULT AS IDENTITY ()"
        )

        doc = type(dialect).format_identity_clause.__doc__
        assert doc is not None
        assert "AS IDENTITY ()" in doc
        assert "literal" in doc
        assert "cannot be execution-confirmed" in doc
        assert (
            "https://cloud.google.com/bigquery/docs/reference/standard-sql/"
            "data-definition-language"
        ) in doc
