# tests/rhosocial/activerecord_bigquery_test/feature/backend/ddl/test_column_attributes.py
"""BigQuery rendering of the dialect-free column-attribute channel.

The identity assertions pin the **documented** Preview spelling (BigQuery
identity columns, announced 2026-08-31/09-02): the option parentheses are
literal in the DDL reference's ``identity_column`` grammar, only their
contents are optional. No BigQuery instance was available to execute the
rendered SQL, so these are render assertions plus a documentation comparison,
not execution verification.

Sources:
* https://cloud.google.com/bigquery/docs/identity-columns
* https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language
"""

import pytest

from rhosocial.activerecord.backend.dialect.exceptions import UnsupportedFeatureError
from rhosocial.activerecord.backend.expression.statements import (
    AutoIncrementClause,
    ColumnDefinition,
)
from rhosocial.activerecord.backend.expression.types import IntegerType
from rhosocial.activerecord.base import CollationAttribute, IdentityAttribute
from rhosocial.activerecord.backend.impl.bigquery.dialect import BigQueryDialect


def _column(dialect, attrs):
    col = ColumnDefinition(dialect, "id", IntegerType(dialect))
    col.attributes = attrs
    return col


def test_collation_is_quoted_string_literal():
    dialect = BigQueryDialect()
    col = _column(dialect, [CollationAttribute(name="und:ci")])
    assert col.to_sql()[0] == "`id` INT64 COLLATE 'und:ci'"


class TestIdentityRendering:
    """The clause BigQuery documents, rendered through the column channel."""

    def test_documented_spelling_with_both_options(self):
        dialect = BigQueryDialect()
        col = _column(
            dialect,
            [IdentityAttribute(generation="BY DEFAULT", start=100, increment=10)],
        )
        assert col.to_sql()[0] == (
            "`id` INT64 GENERATED BY DEFAULT AS IDENTITY "
            "(START WITH 100 INCREMENT BY 10)"
        )

    def test_bare_clause_keeps_the_literal_option_parentheses(self):
        """The grammar makes the parentheses literal; the contents are optional.

        Core's default formatter drops the parentheses when no option is
        requested. BigQuery's grammar does not: ``AS IDENTITY ()`` is the
        minimal documented form, so this dialect's override keeps them.
        """
        dialect = BigQueryDialect()
        col = _column(dialect, [IdentityAttribute()])
        assert col.to_sql()[0] == "`id` INT64 GENERATED BY DEFAULT AS IDENTITY ()"

    def test_always_generation_renders(self):
        dialect = BigQueryDialect()
        col = _column(dialect, [IdentityAttribute(generation="ALWAYS", increment=2)])
        assert col.to_sql()[0] == (
            "`id` INT64 GENERATED ALWAYS AS IDENTITY (INCREMENT BY 2)"
        )


class TestIdentityGates:
    """Every option the documentation does not list is refused, never dropped."""

    @pytest.mark.parametrize(
        "attribute, feature",
        [
            (IdentityAttribute(minvalue=1), "IDENTITY MINVALUE"),
            (IdentityAttribute(maxvalue=10), "IDENTITY MAXVALUE"),
            (IdentityAttribute(cycle=True), "IDENTITY CYCLE"),
            (IdentityAttribute(cycle=False), "IDENTITY CYCLE"),
        ],
        ids=("minvalue", "maxvalue", "cycle", "no-cycle"),
    )
    def test_undocumented_options_are_refused_by_name(self, attribute, feature):
        dialect = BigQueryDialect()
        col = _column(dialect, [attribute])
        with pytest.raises(UnsupportedFeatureError, match=feature):
            col.to_sql()

    def test_withdrawing_the_mechanism_probe_refuses(self):
        """Sentinel: the same construction renders, so the probe is load-bearing.

        A deliberately-wrong dialect answers ``supports_identity_column()``
        ``False``; the formatter must then refuse. The unmutated dialect is
        asserted to render first, so the refusal cannot be a vacuous
        AttributeError from a missing formatter.
        """

        class WithoutIdentity(BigQueryDialect):
            def supports_identity_column(self) -> bool:
                return False

        assert "AS IDENTITY ()" in _column(
            BigQueryDialect(), [IdentityAttribute()]
        ).to_sql()[0]
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY column"):
            _column(WithoutIdentity(), [IdentityAttribute()]).to_sql()

    def test_withdrawing_the_always_probe_refuses_always_only(self):
        """Sentinel: the generation gate is per-mode, not a second master switch."""

        class WithoutAlways(BigQueryDialect):
            def supports_identity_generation_always(self) -> bool:
                return False

        with pytest.raises(UnsupportedFeatureError, match="IDENTITY GENERATED ALWAYS"):
            _column(
                WithoutAlways(), [IdentityAttribute(generation="ALWAYS")]
            ).to_sql()
        assert "BY DEFAULT" in _column(
            WithoutAlways(), [IdentityAttribute(generation="BY DEFAULT")]
        ).to_sql()[0]

    def test_withdrawing_the_start_probe_refuses_start_only(self):
        """Sentinel: a refused option must not disable the other option."""

        class WithoutStart(BigQueryDialect):
            def supports_identity_start(self) -> bool:
                return False

        with pytest.raises(UnsupportedFeatureError, match="IDENTITY START"):
            _column(WithoutStart(), [IdentityAttribute(start=10)]).to_sql()
        assert "INCREMENT BY 2" in _column(
            WithoutStart(), [IdentityAttribute(increment=2)]
        ).to_sql()[0]


class TestAutoIncrementMarker:
    """BigQuery has no ``AUTO_INCREMENT``; the parameterless node refuses."""

    def test_marker_is_refused_by_the_probe(self):
        dialect = BigQueryDialect()
        assert dialect.supports_auto_increment_column() is False
        with pytest.raises(UnsupportedFeatureError, match="AUTO_INCREMENT column"):
            AutoIncrementClause(dialect).to_sql()

    def test_refusal_comes_from_the_probe_not_a_missing_formatter(self):
        """Sentinel: declaring the probe ``True`` makes the core marker render.

        If ``format_auto_increment_clause`` were missing, this construction
        would still raise ``UnsupportedFeatureError`` and the test above would
        pass for the wrong reason. Declaring the capability must switch the
        formatter on, which proves the gate is the discriminator.
        """

        class WithAutoIncrement(BigQueryDialect):
            def supports_auto_increment_column(self) -> bool:
                return True

        assert AutoIncrementClause(WithAutoIncrement()).to_sql() == (" AUTO_INCREMENT", ())
